name: Manual PHPStan Scan

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Folder (contoh: app/Entities)'
        required: true
        default: 'app'
      level:
        description: 'Level Analisa (0-9)'
        required: true
        default: '1'

jobs:
  remote-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, gd, xml, dom

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress
          # Pastikan PHPStan terinstall
          composer require --dev phpstan/phpstan --no-interaction

      - name: ðŸš€ RUN PHPSTAN
        run: |
          echo "Scanning target: ${{ inputs.target }}"
          echo "Strictness Level: ${{ inputs.level }}"
          vendor/bin/phpstan analyse ${{ inputs.target }} --level=${{ inputs.level }} --memory-limit=1G
